### ISSUE TITLE
Give Repo access to the Instructional Team

### ISSUE THREAD

**Issue by ankurshahi80** [group01-project03/vintage-vinyl-records#30]
Email:
ianasqazi@gmail.com
danielceballos94@gmail.com
kishan.doshi88@gmail.com
germanarcila@gmail.com
eapostol@instructors.2u.com
edward.apostol@utoronto.ca

**Comment by amnasyeda** [comment]
Repository can be viewed, accessed, and cloned publicly, however only team-members can make changes.
